networks:
  microservices-networks:
    driver: bridge
services:
  # Build tất cả các service trong một image
  all-services:
    build:
      context: .  # Sử dụng thư mục gốc
      dockerfile: Dockerfile
    image: all-services:latest
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    image: config-server:1.0.0
    ports:
      - "8888:8888"
    restart: on-failure
    env_file:
      - local.env
    networks:
      - microservices-networks
  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    image: service-registry:1.0.0
    ports:
      - "8761:8761"
    restart: on-failure
    env_file:
      - local.env
    networks:
      - microservices-networks
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway:1.0.0
    ports:
      - "8080:8080"
    restart: on-failure
    env_file:
      - local.env
    networks:
      - microservices-networks
  # Các service riêng lẻ
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    image: product-service:1.0.0
    ports:
      - "9898:9898"
    restart: on-failure
    env_file:
      - local.env
    depends_on:
      - all-services
    networks:
      - microservices-networks
