version: '1.0.0'
services:
  multi-module-project:
    build:
      context: ./multi-module-project
      dockerfile: Dockerfile
    image: multi-module-repo:1.0.0
    volumes:
      - maven-repo:/maven-repo
  config-server:
    build:
      context: contextPath
      dockerfile: Dockerfile
    image: configservice:1.0.0
    ports:
      - "8888:8888"
    env_file:
      - local.env
    depends_on:
      - multi-module-project
  service-registry:
    build:
      context: contextPath
      dockerfile: Dockerfile
    image: service-registry:1.0.0
    ports:
      - "8761:8761"
    restart: on-failure
    env_file:
      - local.env
  # api-gateway:
  #   build:
  #     context: contextPath
  #     dockerfile: Dockerfile
  #   image: api-gateway:1.0.0
  #   ports:
  #     - "8080:8080"
  #   restart: on-failure
  #   env_file:
  #     - local.env
  # product-service:
  #   build:
  #     context: contextPath
  #     dockerfile: Dockerfile
  #   image: product-service:1.0.0
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - ./product-service:/app
  #   env_file:
  #     - local.env

volumes:
  maven-repo:
    external: false

