server:
  port: 8080
spring:
  application:
    name: gateway-service
#  data:
#    redis:
#      port: 6379
#      host: localhost
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#        - id: user-service
#          uri: lb://user_service
#          predicates:
#            - Path=/api/nguoidung/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**,/api/v1/categories/**
          # Config rate limit for service product-service
          filters:
#            - name: CircuitBreaker
#              args:
#                name: default
#                fallbackUri: forward:/fallback/product-service
            - name: RequestRateLimiter
              args:
                # Trong 1s nap 10 tokens
                redis-rate-limiter.replenishRate: 10
                # Số lượng token tối đa trong 1s
                redis-rate-limiter.burstCapacity: 20
                # Số lượng token cần để thực hiện 1 request
                redis-rate-limiter.requestedTokens: 1
eureka:
    instance:
      hostname: localhost
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
        register-with-eureka: true
        fetch-registry: true
