server:
  port: 8080
app:
  api-prefix: /api/v1
spring:
  application:
    name: gateway-service
  data:
    redis:
      port: 6379
      host: localhost
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            # Trong 1s nap 10 tokens
            redis-rate-limiter.replenishRate: 10
            # Số lượng token tối đa trong 1s
            redis-rate-limiter.burstCapacity: 20
            # Số lượng token cần để thực hiện 1 request
            redis-rate-limiter.requestedTokens: 1
#        - StripPrefix=1 # Remove prefix /api-gateway from request path
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=${app.api-prefix}/products/**,${app.api-prefix}/categories/**
          filters:
            - PreserveHostHeader
            - StripPrefix=2 # Remove prefix /api/v1 from request path
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=${app.api-prefix}/orders/**,${app.api-prefix}/order-details/**
          filters:
            - StripPrefix=2 # Remove prefix /api/v1 from request path
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/account/**
          # Config rate limit for service product-service
          filters:
            #            - name: CircuitBreaker
            #              args:
            #                name: default
            #                fallbackUri: forward:/fallback/product-service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      register-with-eureka: true
      fetch-registry: true
