server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  data:
    redis:
      port: 6379
      host: localhost
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      route:
        - id: user-service
          uri: lb://user_service
          predicates:
            - Path=/api/nguoidung/**
        - id : product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          # Cấu hình rate limit cho service product-service
          filters:
            - name: RequestRateLimiter
              args:
                # Trong 1s nap 10 tokens
                redis-rate-limiter.replenishRate: 10
                # Số lượng token tối đa trong 1s
                redis-rate-limiter.burstCapacity: 20
                # Số lượng token cần để thực hiện 1 request
                redis-rate-limiter.requestedTokens: 1
  eureka:
    instance:
      hostname: localhost
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
        register-with-eureka: true
        fetch-registry: true
