spring:
  application:
    name: product-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true

#  data:
#    rest:
#      base-path: /api/v1
# Register with Eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
