server:
  port: 9898
  # Datasource configuration
cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${API_KEY_CLOUDINARY}
  api-secret: ${API_SECRET_KEY_CLOUDINARY}
spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIA_DB_PRODUCT_SERVICE:jdbc:mariadb://localhost:3306/product_service?createDatabaseIfNotExist=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    # SQL script to initialize the database
    #  sql:
    #    init:
    # Only run the script for first time
#      mode: always
#      data-locations: classpath:/sql/productDB.sql
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      file-size-threshold: 2KB
#  data:
#    rest:
#      base-path: /api/v1

resilience4j:
  circuitbreaker:
    instances:
      product-service: # name instance
        slidingWindowSize: 10  # size request to keep track
        minimumNumberOfCalls: 5  # minimum number of calls
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50  # % error rate
        waitDurationInOpenState: 10000  # time to wait before retry
        permittedNumberOfCallsInHalfOpenState: 3  # number calls  back
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
  timelimiter:
    instances:
      userService:
        timeoutDuration: 3s  # Giới hạn thời gian
        cancelRunningFuture: true