spring:
  application:
    name: user-service
  config:
    import: configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 3
        initial-interval: 1000
        multiplier: 1.5
