server:
  port: 9000
spring:
  application:
    name: monitor-admin
  config:
    import: optional:configserver:instead
  cloud:
    config:
      enabled: false
# Register with Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


